// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           29
// Async Callback:                       1
// Total number of exported functions:  31

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    lending_pool
    (
        registerAccountToken
        enterMarket
        exitMarket
        addCollateral
        removeCollateral
        borrow
        repay
        liquidate
        updateCollateralWithInterest
        updateBorrowsWithDebt
        getLiqPoolTemplateAddress
        createLiquidityPool
        upgradeLiquidityPool
        setAggregator
        setAssetLoanToValue
        setAssetLiquidationBonus
        getPoolAddress
        getPoolAllowed
        getAssetLoanToValue
        getAssetLiquidationBonus
        getAccountToken
        getAccountPositions
        getDepositPositions
        getBorrowPositions
        getCollateralAmountForToken
        getTotalCollateralAvailable
        getTotalBorrowInDollars
        setPriceAggregatorAddress
        getAggregatorAddress
        callBack
    )
}
