// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           31
// Async Callback (empty):               1
// Total number of exported functions:  33

#![no_std]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    liquidity_pool
    (
        init => init
        getPoolAsset => pool_asset
        getReserves => reserves
        getSuppliedAmount => supplied_amount
        getRewardsReserves => rewards_reserves
        getLendToken => lend_token
        borrowToken => borrow_token
        getPoolParams => pool_params
        getTotalBorrow => borrowed_amount
        getLiquidationThreshold => liquidation_threshold
        getBorrowIndex => borrow_index
        getSupplyIndex => supply_index
        borrowIndexLastUpdateRound => borrow_index_last_update_round
        getAccountToken => account_token
        getDebtNFT => debt_nft_token
        getAccountPositions => account_positions
        updateCollateralWithInterest => update_collateral_with_interest
        updateBorrowsWithDebt => update_borrows_with_debt
        addCollateral => add_collateral
        borrow => borrow
        borrowWithNFTs => borrow_bulk_nfts
        remove_collateral => remove_collateral
        repay => repay
        repayNFTs => repay_nfts
        sendTokens => send_tokens
        getCapitalUtilisation => get_capital_utilisation
        getTotalCapital => get_total_capital
        getDebtInterest => get_debt_interest
        getDepositRate => get_deposit_rate
        getBorrowRate => get_borrow_rate
        setPriceAggregatorAddress => set_price_aggregator_address
        getAggregatorAddress => price_aggregator_address
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
